const productData = [
  {
    name: "Leggings",
    alts: "Womens wear & women's underwear / Women's bottom / Leggings",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Europe",
  },
  {
    name: "Socks",
    alts: "Womens wear & women's underwear / Women's bottom / Socks",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Facebook",
    region: "Europe",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Facebook",
    region: "America",
  },
  {
    name: "Novelty Lighting",
    alts: "Home Improvement / Women's bottom / Novelty Lighting",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Asia",
  },
  {
    name: "Socks",
    alts: "Womens wear & women's underwear / Women's bottom / Socks",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Asia",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Asia",
  },
  {
    name: "Home Gaming Consoles",
    alts: "Phones & Electronics / Gaming & Consoles / Home Game Consoles",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Europe",
  },
  {
    name: "Socks",
    alts: "Womens wear & women's underwear / Women's bottom / Leggings",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Asia",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "Asia",
  },
  {
    name: "Panda",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
    platform: "Tiktok",
    region: "America",
  },
];
export default productData;
