const productData = [
  {
    name: "Leggings",
    alts: "Womens wear & women's underwear / Women's bottom / Leggings",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Socks",
    alts: "Womens wear & women's underwear / Women's bottom / Socks",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Leggings",
    alts: "Womens wear & women's underwear / Women's bottom / Leggings",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Socks",
    alts: "Womens wear & women's underwear / Women's bottom / Socks",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Leggings",
    alts: "Womens wear & women's underwear / Women's bottom / Leggings",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
  {
    name: "Dolls",
    alts: "oys & hobbies / Dolls & stuffed toys / dolls",
    popularity: 224353,
    popularityChange: "2.4%",
    ctr: "32%",
    cvr: "42%",
    cpa: "$34",
    status: "Running",
  },
];
export default productData;
